# Course: Getting Started with TensorFlow 2.0
## Module 2: Exploring the TensorFlow 2.0 Framework

### TensorFlow 1.x vs TensorFlow 2.0
- TensorFlow
    - Novemebr 2015
    - Google OpenSource
    - Static Graph, Sessions, Build then Run, and Low-level Workflows

- PyTorch
    - October 2016
    - Facebook OpenSource
    - Dynamic Graphs & Traditional Python Workflows

- TensorFlow 2
    - Septemeber 2019
    - Static & Dynamic Graphs, Eager Execution, and Traditional Python Workflows w/ Keras

- Graphs
    - Static Graph: Requires phase where you define the graph
    - Dynamic Graph: Graph can be defined and executed as you go

- Keras
    - Original high-level API for multiple frameworks
    - Now tightly-connected to TensorFlow

### Introducing Neural Networks
- Neural Network
    - Often used synonymously with Deep Learning
    - Family of deep learning algorithms - learn from data what features are important
        - Traiditonal classifaciton models use a loss function to provide feedback to the model to improve the model paramaters during the training process
        - Representation systems figure out themselves what to pay attention to, and Neural Networks are an example

- Neural Network Structure
    - Multiple layers of multiple neurons
    - Each layer learns soemthing different from the data
    - The learnings are put together to get final prediction
    - Layers:
        - Input layer (visible)
        - Hidden layers
        - Output layer (visible)

### Neurons and Activation Function

- A neuron is a simple mathematical function and is the building block of a neural network
- Takes several x inputs, the function operates on those inputs and produces a single y output
- For an active neuron, a change in inputs should trigger a corresponding change in the outputs
- The outputs of neurons in one layer feed into the neurons of the next layer
- Connection between neurons are associated with a weight (w), the strength of the connection
    - If the next-layer neuron is sensitve to the output of the first, the connection gets stronger (w increases)
- The neuron structure forms a computation graph
- The graph edges are data called tensors (the neuron output)
- The goal of training is the find the model parameters, meaning all edges have weights helping make predictions
- Each neuron applies two simple functions to the input:
    - Affine transformation
        - Learns linear relationships that exist between inputs and output
        - Weighted sum of the inputs with an added bias (weights and biases are the model parameters)
    - Activation function
        - Output of Affine transformation is fed into activation function
        - Helps discover non-linear relationships between inputs and output
        - This function is custom defined, it is an important model design choice
        - It is non-linear in nature, it's gradient allows it to be sensitive to input changes
        - An "identity function" is one that doesn't change the input, making the neuron a linear neuron (can only learn linear relationships)
        - The funcion should operate in the active region during training, enabling weights to be adjusted
            - The outout does not change when inputs are tweaked in the saturation region
        - Common activation functions:
            - ReLU (most common) - Rectified Linear Unit, returns x or 0 if x < 0 $ max(0,x) $
            - logit (SoftMax) - Outputs a number between 0 and 1, interpreted as probability, s/logit curve
            - tanh
            - step
- The combination of the addine transformation and the activation function can learn any arbitrary relationship

### Demo: Tensors and Tensor Operations
Tensors are multidimensional arrays, similiar to numpy arrays but are meant to be stored and processed on multiple devices (GPUs and CPUs) for distributed neural network training.

Tensors are immtutable.

In [4]:
import tensorflow as tf
import numpy as np

In [5]:
# Add logging for tensor locations
tf.debugging.set_log_device_placement(True)

In [7]:
# Verify the graphs are setup to execute eagerly
tf.executing_eagerly()

True

In [9]:
# Tensors are multi-D array but can also be scalars
x0 = tf.constant(3)

x0

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [10]:
x0.shape

TensorShape([])

In [11]:
x0.dtype

tf.int32

In [13]:
x0.numpy()

3

In [14]:
# Add a scalar
result0 = x0 + 5

result0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 11:15:10.296230: I tensorflow/core/common_runtime/placer.cc:114] x: (_DeviceArg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:15:10.296284: I tensorflow/core/common_runtime/placer.cc:114] y: (_DeviceArg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:15:10.296302: I tensorflow/core/common_runtime/placer.cc:114] AddV2: (AddV2): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:15:10.296312: I tensorflow/core/common_runtime/placer.cc:114] z_RetVal: (_DeviceRetval): /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [16]:
# Create vector (1D array) tensor 
x1 = tf.constant([1.1, 2.2, 3.3, 4.4])

x1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 11:17:14.370972: I tensorflow/core/common_runtime/placer.cc:114] input: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:17:14.370998: I tensorflow/core/common_runtime/placer.cc:114] _EagerConst: (_EagerConst): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:17:14.371007: I tensorflow/core/common_runtime/placer.cc:114] output_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [17]:
# Add a scaler to the vector via broadcasting
result1 = x1 + 5

result1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 11:18:04.470089: I tensorflow/core/common_runtime/placer.cc:114] x: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:18:04.470130: I tensorflow/core/common_runtime/placer.cc:114] y: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:18:04.470147: I tensorflow/core/common_runtime/placer.cc:114] AddV2: (AddV2): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:18:04.470158: I tensorflow/core/common_runtime/placer.cc:114] z_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [19]:
# Add two tensors
result1 = x1 + tf.constant(5.0)

result1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [23]:
# Add using add method rather than +
result1 = tf.add(x1, tf.constant(5.0))

result1

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [21]:
# Create 2D tensor
x2 = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])

x2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [22]:
# Change the tensor data type
x2 = tf.cast(x2, tf.float32)

x2

Executing op Cast in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 11:21:55.545433: I tensorflow/core/common_runtime/placer.cc:114] x: (_DeviceArg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:21:55.545462: I tensorflow/core/common_runtime/placer.cc:114] Cast: (Cast): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:21:55.545471: I tensorflow/core/common_runtime/placer.cc:114] y_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [25]:
# Multipy tensors - note tensor shapes need to be compatible for a given operation
result3 = tf.multiply(x1, x2)

result3

Executing op Mul in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 11:28:42.645377: I tensorflow/core/common_runtime/placer.cc:114] x: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:28:42.645405: I tensorflow/core/common_runtime/placer.cc:114] y: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:28:42.645420: I tensorflow/core/common_runtime/placer.cc:114] Mul: (Mul): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:28:42.645430: I tensorflow/core/common_runtime/placer.cc:114] z_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.1     ,  4.4     ,  9.9     , 17.6     ],
       [ 5.5     , 13.200001, 23.1     , 35.2     ]], dtype=float32)>

In [26]:
x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [28]:
# Convert tensor to numpy array
arr_x1 = x1.numpy()

arr_x1

array([1.1, 2.2, 3.3, 4.4], dtype=float32)

In [29]:
arr_x4 = np.array([[10, 20], [30, 40], [50, 60]])

arr_x4

array([[10, 20],
       [30, 40],
       [50, 60]])

In [30]:
# Convert numpy array to tensor
x4 = tf.convert_to_tensor(arr_x4)

x4

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 11:35:22.087189: I tensorflow/core/common_runtime/placer.cc:114] input: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:35:22.087217: I tensorflow/core/common_runtime/placer.cc:114] _EagerConst: (_EagerConst): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:35:22.087226: I tensorflow/core/common_runtime/placer.cc:114] output_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]])>

In [38]:
# numpy operations are compatible with tensors

print("original: ", x2)
print("square: ", np.square(x2))
print("sqrt: ", np.sqrt(x2))

# but not recommended as they are not part of the tensorflow computation graph and can cause issues

original:  tf.Tensor(
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4), dtype=float32)
square:  [[ 1.  4.  9. 16.]
 [25. 36. 49. 64.]]
sqrt:  [[1.        1.4142135 1.7320508 2.       ]
 [2.236068  2.4494898 2.6457512 2.828427 ]]


In [39]:
# Check if variable is a tensor
tf.is_tensor(arr_x4)

False

In [40]:
tf.is_tensor(x4)

True

In [44]:
# Helper to initialize tensor with zeros in specified shape
t0 = tf.zeros([3, 5], tf.int32)

t0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [45]:
# Same with ones
t1 = tf.ones([3, 5], tf.int32)

t1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [46]:
# Reshape a tensor (must match original number of elements)
t0_reshaped = tf.reshape(t0, (5, 3))

t0_reshaped

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Reshape in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 11:43:15.856982: I tensorflow/core/common_runtime/placer.cc:114] tensor: (_DeviceArg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:43:15.857013: I tensorflow/core/common_runtime/placer.cc:114] shape: (_DeviceArg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:43:15.857028: I tensorflow/core/common_runtime/placer.cc:114] Reshape: (Reshape): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 11:43:15.857039: I tensorflow/core/common_runtime/placer.cc:114] output_RetVal: (_DeviceRetval): /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

### Demo: Variables
Vriables are the recommended way to share persistent state in a TensorFlow program.

Variables are mutable, can be thought of a mutable container holding tensors.

Tensors held by a variable can be mutated or changes by running operations on the variable.

In [48]:
# Instantiate a variable

v1 = tf.Variable([[1.5, 2, 5], [2, 6, 8]])

v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 13:50:31.068165: I tensorflow/core/common_runtime/placer.cc:114] resource: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:50:31.068192: I tensorflow/core/common_runtime/placer.cc:114] ReadVariableOp: (ReadVariableOp): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:50:31.068199: I tensorflow/core/common_runtime/placer.cc:114] value_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:50:31.073443: I tensorflow/core/common_runtime/placer.cc:114] input: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:50:31.073466: I tensorflow/core/common_runtime/placer.cc:114] Identity: (Identity): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:50:31.073473: I tensorflow/core/common_runtime/placer.cc:114] output_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [52]:
# You can specify a type otherwise it will infer it
v2 = tf.Variable([1, 2, 3], [4, 5, 6], dtype=tf.float32)

v2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [53]:
# Operate on variables (operates on the underlying tensors)
tf.add(v1, v2)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.5,  4. ,  8. ],
       [ 3. ,  8. , 11. ]], dtype=float32)>

In [55]:
# Convert variable to tensor
tf.convert_to_tensor(v1)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [56]:
# Get the numpy representation of the underlying tensor
v1.numpy()

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)

In [57]:
# Observe the original tensor value within this variable
v1

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [59]:
# Notice that we can mutate it, in this case by assigning new values
v1.assign([[10, 20, 30], [40, 50, 60]])

v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 13:58:09.155837: I tensorflow/core/common_runtime/placer.cc:114] resource: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:58:09.155861: I tensorflow/core/common_runtime/placer.cc:114] value: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:58:09.155873: I tensorflow/core/common_runtime/placer.cc:114] AssignVariableOp: (AssignVariableOp): /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)>

In [60]:
# And in this case we assign a value to a specific element within the underlying tensor
v1[0, 0].assign(100)

v1

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ResourceStridedSliceAssign in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 13:59:11.629980: I tensorflow/core/common_runtime/placer.cc:114] input: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:59:11.630006: I tensorflow/core/common_runtime/placer.cc:114] begin: (_DeviceArg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:59:11.630015: I tensorflow/core/common_runtime/placer.cc:114] end: (_DeviceArg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:59:11.630022: I tensorflow/core/common_runtime/placer.cc:114] strides: (_DeviceArg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:59:11.630032: I tensorflow/core/common_runtime/placer.cc:114] StridedSlice: (StridedSlice): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:59:11.630039: I tensorflow/core/common_runtime/placer.cc:114] output_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 13:59:11.638401: I tensorflow/core/common_runtime/placer.cc:114] ref: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-0

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[100.,  20.,  30.],
       [ 40.,  50.,  60.]], dtype=float32)>

In [61]:
# And mutate with arithmetic - add
v1.assign_add([[1, 1, 1], [1, 1, 1]])

v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignAddVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 14:00:12.491352: I tensorflow/core/common_runtime/placer.cc:114] resource: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 14:00:12.491377: I tensorflow/core/common_runtime/placer.cc:114] value: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 14:00:12.491390: I tensorflow/core/common_runtime/placer.cc:114] AssignAddVariableOp: (AssignAddVariableOp): /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[101.,  21.,  31.],
       [ 41.,  51.,  61.]], dtype=float32)>

In [62]:
# subtract
v1.assign_sub([[2, 2, 2], [2, 2, 2]])

v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignSubVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 14:01:21.801391: I tensorflow/core/common_runtime/placer.cc:114] resource: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 14:01:21.801415: I tensorflow/core/common_runtime/placer.cc:114] value: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 14:01:21.801427: I tensorflow/core/common_runtime/placer.cc:114] AssignSubVariableOp: (AssignSubVariableOp): /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[99., 19., 29.],
       [39., 49., 59.]], dtype=float32)>

In [63]:
var_a = tf.Variable([2.0, 3.0])

var_a

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


2023-09-21 14:01:43.095420: I tensorflow/core/common_runtime/placer.cc:114] resource_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 14:01:43.095532: I tensorflow/core/common_runtime/placer.cc:114] VarHandleOp: (VarHandleOp): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 14:01:43.100108: I tensorflow/core/common_runtime/placer.cc:114] resource: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 14:01:43.100175: I tensorflow/core/common_runtime/placer.cc:114] value: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 14:01:43.100191: I tensorflow/core/common_runtime/placer.cc:114] AssignVariableOp: (AssignVariableOp): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 14:01:43.112278: I tensorflow/core/common_runtime/placer.cc:114] resource: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0
2023-09-21 14:01:43.112324: I tensorflow/core/common_runtime/placer.cc:114] ReadVariableOp: (ReadVariableOp): /job:localhost/repl

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [64]:
# Assign a variable the value of another variable (copy, not a reference, they do not share memory)
var_b = tf.Variable(var_a)

var_b

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [71]:
# Note when a new value is assigned to var_b it does not change var_a (because it was a copy)
var_b.assign([200, 300])

print()
print("variables:")
print("var_a: ", var_a)
print()
print("var_b: ", var_b)
print()
print("numpy:")
print("var_a: ", var_a.numpy())
print()
print("var_b: ", var_b.numpy())

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0

variables:
var_a:  Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

var_b:  Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([200., 300.], dtype=float32)>

numpy:
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
var_a:  [2. 3.]

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /j

### TensorFlow and Keras

**TensorFlow** allows us to perform scientific computations at scale, most commonly in the form of neural network models.

**Keras** is a central part of the tightly-conected TensorFlow 2.0 ecosystem, covering every part of the machine learning workflow.

TensorFlow 2.0 includes the Keras API:
- Estimators
- Pipelines
- Eager execution 

Use tf.keras to build, train, and evaluate models. Also use to save models to disk, restore models, and leverage GPUs.

## Module 3: Understanding Dynamic and Static Computation Graphs
All of the computations and tensors in a nueral network together make up a directed-acyclic graph (DAG).
- Optimize operations in TenrsorFlow
- Removes common expressions
- Parallelizes independent computations to run on different devices
- Simplifies distributed training and deployment

### Static and Dynamic Computation Graphs
TensorFlow 2.0 supports both whereas 1.0 only supported static graphs.

**Best Practice:** Develop with dynamic graphs, deploy static.

#### Static Graphs
*Define, then run*
- Lazy execution
- Compilation converts the graph into executable format
- Harder to program and debug, less flexibile
- More efficient and easier to optimize
- Symbolic programming of NNs
    - Define operations then execute
    - Define function abstractly where no actual computation takes place
    - Computation explicitly compiled before evaluation
    - e.g., Java, C++

#### Dyanmic Graphs
*Define by run*
- Eager execution
- Graph already in executable format
- Easier to write and debug, more flexibile
- Less efficient and harder to optimize
- Imperative programming of NNs
    - Execution performed as operations defined
    - Code actually executed as the function is defined
    - No explicit comilation step before evaluation
    - e.g., Python

### Demo: TensorFlow V1 Sessions to Execute Static Computation Graphs

In [72]:
import tensorflow as tf